### ISSUE TITLE
Why only for one word only?.

### ISSUE THREAD

**Issue by aditya624** [msg-systems/coreferee#10]
why only for one word only?. like this,
<img width="852" alt="Screen Shot 2021-06-28 at 09 48 55" src="https://user-images.githubusercontent.com/53865102/123572602-b09df280-d7f6-11eb-8d4f-41b0bd53ad02.png">
what if I want in cluster 0 : Andy Pena(1), he(9) ?

**Comment by richardpaulhudson** [comment]
The original idea was that the token references (e.g. `Pena(1)`) were entry points from which to explore the surrounding spaCy parse tree. However, several people seem to have this requirement, and in fact multiword proper names are examined during processing, so I will plan an enhancement to output this information within the coref chains.

In the meantime this workaround should help:

```
rules_analyzer = nlp_en.get_pipe('coreferee').annotator.rules_analyzer
rules_analyzer.get_propn_subtree(doc[1])
```

**Comment by KTRosenberg** [comment]
What would be a fully general solution to this without knowing which words are compound? I need to serialize into json and send to a client, and at that point I won’t be able to query Spacy anymore. So I would need to modify the output array somehow.

**Comment by richardpaulhudson** [comment]
The code above should return None for words that do not head compound proper-noun phrases.

**Comment by richardpaulhudson** [comment]
In the end I decided not to incorporate this functionality into the main data model, but rather added a section to the documentation setting out the above code as a way to implement it.
