### ISSUE TITLE
Not able to install coreferee

### ISSUE THREAD

**Issue by ansh-lehri** [msg-systems/coreferee#12]
I am trying to install coreferee using commands mentioned in the documentation:

```
python3 -m pip install coreferee
python3 -m coreferee install en
```

but executing this is showing the following errors:

**ERROR: Could not find a version that satisfies the requirement coreferee (from versions: none)
ERROR: No matching distribution found for coreferee**

How to resolve this issue?

**Comment by richardpaulhudson** [comment]
Duplicate of #2
