### ISSUE TITLE
coreferee install de raises ImportError

### ISSUE THREAD

**Issue by YannHau** [msg-systems/coreferee#13]
Hello,
I am having some trouble installing the german additional data. Receiving ImportError when running:
`python3 -m coreferee install de`
Error log is:
`ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'`

I am running this in an _venv_ with python3.8.5 .

**Comment by richardpaulhudson** [comment]
I have just released version 1.1.0, which should have solved the problem.
