### ISSUE TITLE
Use coreferee with spacy >3.1.2

### ISSUE THREAD

**Issue by YannHau** [msg-systems/coreferee#18]
Hey there, 
I am having problems to use coreferee together with newest spacy version (3.1.2).
To add a Language factory it is necassary to use Decorators as suggested by spacy. 

So I am not that experienced with programming and python as well. But for me I have to write a function where I initialize an object. Then it is possible to apply spacy Decorator `@Language.factory` on the function. 

I figured out to do this for different packages, except this.  For example it works for _spacy-langdetect_ like this:
`from spacy_langdetect import LanguageDetector
@Language.factory("language_detector")
    def init_LanguageDetector(nlp, name):
        return LanguageDetector(language_detection_function=None)`

and afterwards I can add this new factory easily to the existing pipeline with:
`nlp.add_pipe()` 

Is there a similar way to do this for coreferee, because snippets provided by the READ ME do not work..?

Thanks in advance!

**Comment by liongkj** [comment]
I also faced the similar error as op. However, if i import in a python console, it is working as shown in the readme.

**Comment by richardpaulhudson** [comment]
Hi there,

for coreferee the @Language.factory class is already part of the package (https://github.com/msg-systems/coreferee/blob/master/coreferee/manager.py from line 99). This means once you have imported coreferee you can use `nlp.add_pipe()` immediately.

Which of the snippets provided by README.md does not work and what is the error/issue you are experiencing when you try to run it?

**Comment by liongkj** [comment]
Hi, the nlp.add_pipe() throws an error at the nlp.add_pipe() line. I have downloaded both spacy en_core_web_trf and coreferee en package
````python

nlp = spacy.load("en_core_web_trf")
nlp.add_pipe('coreferee')
````
Error code
````
ValueError: [E002] Can't find factory for 'coreferee' for language English (en). This usually happens when spaCy calls 'nlp.create_pipe' with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator '@Language.component' (for function components) or '@Language.factory' (for class components).

````

**Comment by YannHau** [comment]
I'm trying to apply coreferee for the german language. 

```
import spacy, coreferee
nlp = spacy.load("de_core_news_lg")
nlp.add_pipe('coreferee')
```
The error following is different to the one shown in the other comment. 

`coreferee.errors.ModelNotSupportedError: de_core_news_lg version 3.1.0`

I will try it with an older pipeline version now 

------------------------------

@liongkj have you imported spacy-transformers in your code?

**Comment by liongkj** [comment]
> I'm trying to apply coreferee for the german language.
> 
> ```
> import spacy, coreferee
> nlp = spacy.load("de_core_news_lg")
> nlp.add_pipe('coreferee')
> ```
> 
> The error following is different to the one shown in the other comment.
> 
> `coreferee.errors.ModelNotSupportedError: de_core_news_lg version 3.1.0`
> 
> I will try it with an older pipeline version now
> 
> @liongkj have you imported spacy-transformers in your code?

I am very sorry, I thought it meant the same error. I will open a new issue.

**Comment by YannHau** [comment]
> am very sorry, I thought it meant the same error. I will open a new issue.

No worries! I had the same error earlier these days. But can not remember when it stopped.

**Comment by richardpaulhudson** [comment]
Hi there, for both problems, please try the following and get back to me if it still doesn't work:

From the command line:

- check you are using Python version 3.9
- `python3 -m pip install coreferee` or `python -m pip install coreferee`
- `python3 -m coreferee install en` or `python -m coreferee install en` (for English)
- `python3 -m coreferee install de` or `python -m coreferee install de` (for German)

From the Python script or console:

`import coreferee`
`import spacy`

**Comment by YannHau** [comment]
Well that works perfectly somehow now! Thanks a lot.

I first completely uninstalled spacy and coreferee and installed it with your suggested commands. 
No idea where the difference is but it was nothing about the used versions. Anyway thanks!
