### ISSUE TITLE
coreferee.errors.ModelNotSupportedError: en_core_web_trf version 3.1.0

### ISSUE THREAD

**Issue by e3oroush** [msg-systems/coreferee#19]
I tried to use this library but got the following error:
```python
coreferee.errors.ModelNotSupportedError: en_core_web_trf version 3.1.0
```
Here are my environment details:
```
Python 3.8.5
spaCy 3.1.1
```
I'm not sure about the `coreferee` version, but it should be the current last version, `v.1.1.0`.
I also used the Python 3.9.6 and master branch of the repo and tried to install the package inline, but still got the same error.
Any idea what am I doing wrong?

**Comment by richardpaulhudson** [comment]
Hi, the latest version of Coreferee only works with Python 3.9; Python 3.8 is no longer supported. You also need to install the Coreferee models for the language you want to use, e.g.

`python3 -m coreferee install en`

**Comment by adavoudi** [comment]
I had the same problem. Seems like the library is dependant on version `3.1.0` of the spacy models, but `python -m spacy download ` will install version `3.0.0` of the models. Therefore you need to install that specific version directly from git like below:

```bash
pip3 install https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.1.0/en_core_web_lg-3.1.0.tar.gz
```

The above is for the `en_core_web_lg`. Just replace it with whatever model you want.

**Comment by richardpaulhudson** [comment]
´python -m spacy download´ should normally download the latest version of the model. I don't really understand why this didn't work for @adavoudi, but whatever the problem is it would be a spaCy issue rather than a coreferee issue.
