### ISSUE TITLE
How to clean up GPU memory after this runs?

### ISSUE THREAD

**Issue by ohmeow** [msg-systems/coreferee#3]
The method is using all available GPUs and I notice that the GPU memory isn't cleaned up after it runs.

Is there any way to:

1. Specify what GPUs should be used (and also the max memory to consume)?
2. Clear out the GPU memory after this runs?

Thanks much.  The results are pretty impressive.

**Comment by AliHaider20** [comment]
cuda.clear_cache()

**Comment by ohmeow** [comment]
Where are you getting `cuda` from?  I tried `numba` but there is no `clear_cache` method.

**Comment by ohmeow** [comment]
Hey @richardpaulhudson ... I'm more of a PyTorch guy myself, but this approach is working below.  Can it be improved? Probably.

```
def _resolve_coreferences(texts):
    nlp = spacy.load(model_name)
    nlp.add_pipe('coreferee')

    updated_docs = []
    for idx, doc in enumerate(nlp.pipe(texts)):
        new_doc = []
        for token in doc:
            tok = doc._.coref_chains.resolve(token) or token
            tok_text = ' and '.join([t.text for t in tok]) if(isinstance(tok, list)) else tok.text
            tok_text += token.whitespace_
            new_doc.append(tok_text)

        updated_docs.append(''.join(new_doc))

    return updated_docs

def resolve_coreferences(texts):
    from multiprocessing import Pool
    
    with Pool(1) as p:
        results = p.apply(_resolve_coreferences, args=(texts,))
    return results
```

**Comment by richardpaulhudson** [comment]
Hi @ohmeow, thanks for the example code above. I believe this shows that the memory is being allocated by the parsed documents - pulling out the relevant information from them in this way allows the documents to be garbage-collected.

I believe that this may well be the problem described in https://github.com/explosion/spaCy/issues/7593. When a transformer model parses a document, it retains large amounts of transformer-related information within the document which some users will want to examine. This has the disadvantage that documents have a large memory footprint. If you are not interested in the transformer-related information, you can remove it after each document has been parsed by setting `doc._.trf_data = None`.

**Comment by richardpaulhudson** [comment]
Closing as no further answer received.
