### ISSUE TITLE
Support for python 3.7 for google colab use

### ISSUE THREAD

**Issue by steflayanto** [msg-systems/coreferee#34]
Google colab only supports python3.7, was wondering if it were possible to release a version of coreferee that supported that?
The other big coreference library compatible with spacy that I am aware of is neuralcoref and that is only supported in spacy 2. They're working on a new version for spacy 3.0 but nothing has been heard on that for a while, so there's a niche right now for a spacy 3 & colab friendly neural coref library

**Comment by richardpaulhudson** [comment]
Hi @steflayanto, I am now working directly at Explosion and we are trying to work out the best way of integrating Coreferee with spaCy in the future. Whatever is decided, it is clear we need to support a wider range of Python versions.

**Comment by richardpaulhudson** [comment]
Hi, I will be releasing a new Coreferee version within the next few weeks that will support all Python versions from 3.6 to 3.10.

**Comment by richardpaulhudson** [comment]
Version 1.2.0 is now available and supports Python 3.7.
