### ISSUE TITLE
Not able to add spaCy pipw

### ISSUE THREAD

**Issue by amareshp72** [msg-systems/coreferee#35]
I tried python -m coreferee install en as well as pip install of the zip file but still getting this error
![coreferee](https://user-images.githubusercontent.com/49395581/143190905-4242fdf9-cf4d-4eff-9e37-458b79350d51.png)

**Comment by richardpaulhudson** [comment]
Have you tried issuing the command shown under `In [3]`? If so, what happened then?

**Comment by richardpaulhudson** [comment]
Closing as no further answer received.
