### ISSUE TITLE
Cannot install on Apple Silicon

### ISSUE THREAD

**Issue by KTRosenberg** [msg-systems/coreferee#37]
I am trying to install this library on macOS 11 on an Apple Silicon Mac. The requirements seem to conflict no matter what I try.

The following are all the things I've tried. It would be great if you provided a way to install from source because I got M1 tensorflow and spacy to work just fine. I just don't know how to install coreferee and the respective models with the libraries that I do have available.
```
INFO: pip is looking at multiple versions of coreferee to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement h5py~=3.1.0 (from tensorflow-macos) (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.3.0, 3.4.0, 3.5.0, 3.6.0)
ERROR: No matching distribution found for h5py~=3.1.0
```
I tried building h5py from source using the home-brew version using
`HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.1 pip3.9 install --no-binary=h5py h5py==3.1.0`
because there was no prebuilt binary available. That worked.

But installing carefree doesn't seem to see this version, and I wind up with the error above.
I very much depend on this library. It would be great if we could get this working again.
How can the issue be resolved?

I think it's a problem with several libraries including tensorflow.

EDIT: I tried installing the intel python3.9 hoping Rosetta would force everything to work under x86_64 emulation mode. Everything installed except for:
`python3 -m coreferee install en`, which yielded "zsh: illegal hardware instruction".

EDIT2: I noticed that 1.1.1 was explicitly for resolving Apple Silicon issues. Why am I experiencing these installation problems then? Is there something subtle that I am missing?

I'm out of ideas.

EDIT3: This is the official tensorflow instructions for Apple Silicon 
[link](https://developer.apple.com/metal/tensorflow-plugin/)  , 
but the procedure requires Conda. 
I'd still like to know what is going wrong if you were successful in installing on Apple Silicon for v. 1.1.1.
Spacy seems to be having trouble with transformers too.

EDIT4: It took a while, but I got things working by just ignoring using pip and just downloading the repo and dependencies separately using whatever is recommended for mac:
```

curl -O https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
./Miniforge3-MacOSX-arm64.sh
conda config --set auto_activate_base false
conda create --name my_env python=3.9
conda activate my_env
conda install rust 
export CARGO_BUILD_TARGET="aarch64-apple-darwin"
conda install -c conda-forge spacy=3.1.4

python -m spacy download en_core_web_trf
python -m spacy download en_core_web_lg

conda install -c apple tensorflow-deps
pip install tensorflow-macos
pip install tensorflow-metal
git clone https://github.com/msg-systems/coreferee.git
mv ./coreferee ./coreferee_container
cd ./coreferee_container
python -m coreferee install en
cd ..
```

I hope this process becomes simpler. Also, hopefully you'll update to spacy 3.20.

---------------------------

OLD:
I get this error on macOS 11.3 on an M1 (ARM) machine when I try installing:
```
pip3 install coreferee
python3 -m coreferee install en
```
```
ERROR: Cannot install coreferee==1.1.0, coreferee==1.1.1 and coreferee==1.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    coreferee 1.1.2 depends on tensorflow-macos~=2.6.0; platform_system == "Darwin"
    coreferee 1.1.1 depends on tensorflow-macos~=2.6.0; platform_system == "Darwin"
    coreferee 1.1.0 depends on tensorflow~=2.5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```
How can I resolve this?

Also, I am using python 3.10, but the same thing happens with 3.9.
I am also hoping Spacy 3.2 support is around the corner.

EDIT: I specified an older version of coreferee (1.1.0), but now I get:
```
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.5.0 (from coreferee) (from versions: none)
ERROR: No matching distribution found for tensorflow~=2.5.0
```
It seems a lot of these package requirements don't exist. I really depend on this project. How can we get it working?

EDIT:
It looks like the issue is h5py. There's no pre-built wheel for it on ARM Macs.
It's unclear how to install it from source for this purpose.

**Comment by philippnoah** [comment]
Think this can be closed now.

**Comment by KTRosenberg** [comment]
I'm not sure this is resolved. Coreferee installation on macOS using the ARM chips still fails. Are you planning on supporting that platform officially?
Also, do you anticipate supporting the latest Spacy?

**Comment by philippnoah** [comment]
I'm not part of coreferee unfortunately 😞 but I thought that Edit 4 suggested things were working now. I'm currently stuck trying to get it running myself.

**Comment by KTRosenberg** [comment]
> I'm not part of coreferee unfortunately 😞 but I thought that Edit 4 suggested things were working now. I'm currently stuck trying to get it running myself.

No, unfortunately it's not resolved. I had to install from source and do a bunch of painful things externally using mac-specific "hacks." pip installation completely fails due to the tensorflow dependency, and I had to use conda. Also, the fact that only Spacy < 3.2 is supported seems to prevent gpu acceleration or something. I hope this can be resolved and potentially updated for compatibility with 3.2.

**Comment by philippnoah** [comment]
🎉  I just got it to work with:
```
miniconda==4.11.0
python==3.9
numpy==1.21.4
tensorflow-macos==2.7.0
spacy== 3.2.1
coreferee==1.1.2
```
I had to install the other dependencies before `coreferee`, then run `pip install coreferee==1.1.2 --no-deps`. Hope this works for you too.

**Comment by KTRosenberg** [comment]
> 🎉 I just got it to work with:
> 
> ```
> miniconda==4.11.0
> python==3.9
> numpy==1.21.4
> tensorflow-macos==2.7.0
> spacy==3.2.1
> coreferee==1.1.2
> ```
> 
> I had to install the other dependencies before `coreferee`, then run `pip install coreferee==1.1.2 --no-deps`. Hope this works for you too.

Could you show the full steps for installation? I just don’t want room for ambiguity since I had to do a lot of crazy side maneuvers as shown above. I am also pretty sure I did something similar to what you did and the pip tensorflow package always failed.
Did you use miniforge for conda as well?

**Comment by philippnoah** [comment]
My bad. I must have looked at old output, I'm using `spacy==3.1.0`. Updated my previous comment.

**Comment by KTRosenberg** [comment]
> My bad. I must have looked at old output, I'm using `spacy==3.1.0`. Updated my previous comment.

Still, would you show the steps? Also, you should be able to get it to 3.1.4

For 3.2 support, I think the author needs to do that explicitly.

**Comment by KTRosenberg** [comment]
> Steps that work for me (just tested) are:
> 
> ```
> conda create -n coreferee python=3.9
> conda activate coreferee
> conda install -c apple tensorflow-deps==2.6.0
> pip install tensorflow-macos==2.7.0
> conda install -c conda-forge spacy==3.1.0
> python -m spacy download fr_core_news_lg
> pip install coreferee --no-deps
> python -m coreferee install fr
> ```
> 
> Let me know.

Thanks. You may want to try 3.1.4 though. Also, make sure the transformers models work for you.

Does it matter if you use miniforge, mambaforge, etc. to install conda?

**Comment by philippnoah** [comment]
Just tested with `spacy==3.1.4` and `en_core_web_trf`, worked for me.
I only tested with `miniforge`, I'm not sure if it works with the others.

**Comment by KTRosenberg** [comment]
For me I get a warning that there’a no CUDA device, which means it’s reverting to doinv everything on the CPU. I guess I have to reinstall everything somehow because that can’t be right.

**Comment by KTRosenberg** [comment]
@richardpaulhudson Hi. I got it working sort of, but only via miniforge/conda so I could use the newer tensorflow for Apple chips, and I have to install from sourcd
I still encounter issues with installation though, like numpy going out of sync. (I have to do an uninstall, then reinstall “hack.”) I am hoping coreferee might be upgraded to work with Spacy 3.2 because that woild also help.

My fear is that eventually 3.1.4 will stop being available, and then Ia will be stuck.

I do get much better results with the transformers version, so I am trying to stick with that one.

**Comment by richardpaulhudson** [comment]
Sorry about all this! I'm currently working on a new version of Coreferee which uses Thinc rather than TensorFlow, meaning that it doesn't have any dependencies except spaCy itself and the transitive dependencies that entails. I think this should solve these problems.

**Comment by KTRosenberg** [comment]
> Sorry about all this! I'm currently working on a new version of Coreferee which uses Thinc rather than TensorFlow, meaning that it doesn't have any dependencies except spaCy itself and the transitive dependencies that entails. I think this should solve these problems.

Thanks for the update. I'm looking forward to that new version!

**Comment by richardpaulhudson** [comment]
Version 1.2.0 is now available and these problems should no longer be relevant.
