### ISSUE TITLE
How to cite coreferee

### ISSUE THREAD

**Issue by vedmathai** [msg-systems/coreferee#40]
Awesome project and appreciate the detailed readme!

I'd like to use coreferee in an academic project and, therefore, would like to know how best to cite it. I am not sure if I missed this somewhere, but it would be helpful if you can add this information to the readme file.

**Comment by richardpaulhudson** [comment]
Hi @vedmathai, glad you're finding Coreferee useful. There isn't a paper or anything about Coreferee, so the best citation is probably the Github repository. As I'm now maintaining Coreferee at Explosion, the repository there is probably the better one to cite: https://github.com/explosion/coreferee.
