### ISSUE TITLE
Cannot install dependency while pip install coreferee

### ISSUE THREAD

**Issue by demongolem-biz** [msg-systems/coreferee#42]
When doing pip install coreferee, I get the folowing stack trace when I get to wrapt.  On RHEL 7.6.  Any additional requirements for being able to pip install?  An additional note, I can pip install 1.13.3 of wrapt but as you see it is attempting to use 1.12.1.  Don't you need 1.13 with Python 3.9 or should I not be using Python 3.9?

Collecting wrapt~=1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/gregory.werner/opt/python-3.9.10/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-enq9faee/wrapt_779f91a727f145c49bac8be4aea62efd/setup.py'"'"'; __file__='"'"'/tmp/pip-install-enq9faee/wrapt_779f91a727f145c49bac8be4aea62efd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w5mkwcfp
         cwd: /tmp/pip-install-enq9faee/wrapt_779f91a727f145c49bac8be4aea62efd/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/gregory.werner/opt/python-3.9.10/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/home/gregory.werner/opt/python-3.9.10/lib/python3.9/site-packages/setuptools/dist.py", line 38, in <module>
        from setuptools import windows_support
      File "/home/gregory.werner/opt/python-3.9.10/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/gregory.werner/opt/python-3.9.10/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'

**Comment by richardpaulhudson** [comment]
This looks as though it might be an issue with the underlying Python installation rather than specifically with Coreferee. Are you using a virtual environment — could you try with a clean one? Are other Python libraries working as expected? Could you try reinstalling Python?

**Comment by richardpaulhudson** [comment]
Closing as no further answer received.
