### ISSUE TITLE
Documentation website?

### ISSUE THREAD

**Issue by XsongyangX** [msg-systems/coreferee#46]
Hi! I stumbled upon this repo after looking up tools for corefs, which ended up not working or were completely confusing. This one seems approachable. Is there a documentation website for coreferee?

**Comment by Pantalaymon** [comment]
As far as I am aware there is no documentation website for coreferee.
Are you looking for specific functionalities that are not in the README ?

**Comment by XsongyangX** [comment]
I understand the basics of the tool. I wish I can know more

**Comment by richardpaulhudson** [comment]
The documentation is all in the README.
