### ISSUE TITLE
Scores for each co-reference

### ISSUE THREAD

**Issue by Yourivdzee** [msg-systems/coreferee#48]
Hi,

I was wondering whether it is possible to retrieve a output score for found references.

Thanks in advance

**Comment by Pantalaymon** [comment]
Hi,

Do you mean to evaluate coreference when you have an annotated dataset?

**Comment by richardpaulhudson** [comment]
Hi, Coreferee is designed as a black-box component makes a best guess for each anaphor and deletes everything else. During processing the scores are stored under `Token._.coref_chains.temp_score` but they are deleted by the Annotator as the final step in document processing.

If you wish to retain the scores, you could follow these steps:

- clone the repository
- delete the section of code towards the end of `annotator.py` that deletes the `temp_*` properties as the final step in processing
- install your altered codebase using `pip install .` from the root directory of the library
