### ISSUE TITLE
Doesn't recognize I, me, myself?

### ISSUE THREAD

**Issue by wiseguybec** [msg-systems/coreferee#5]
Hey there, amazing work! Three things are apparent:

- When given a longer text, if the name "Florian" appears in different sentences the chains are split and "Florian" repeated. So the chains are per sentence, correct?

- In a text with "I", "myself" and "me" the coreferences are completely ignored. Correct?

- If a first name and last name, e.g. "Florian Schmitt" is used, the chain is only based on "Schmitt" and ignores "Florian"

Am I doing smth wrong, or are these findings as designed?

**Comment by richardpaulhudson** [comment]
Hi @wiseguybec, glad to hear you are finding Coreferee useful; sorry it's taken me so long to get back to you, I've just got back from vacation.

Taking your questions one by one:

- The chains are not per sentence, but nouns analysed as coreferring can only be a maximum of 2 sentences apart (`maximum_coreferring_nouns_sentence_referential_distance` in `rules.py`), while anaphor coreference is permitted up to 5 sentences apart. 

- Yes, see the comments at the end of the section https://github.com/msg-systems/coreferee#background-information.

- Yes, matching between multiword proper nouns is restricted to situations where the ends of the multiwords match to prevent a situation where e.g. `Richard Paul Hudson came in. Richard Paul Hudson went back out` produces a large set of matches `{'Richard Paul Hudson', 'Richard Paul', 'Paul Hudson', 'Richard', Paul', 'Hudson'}`.
