### ISSUE TITLE
ModelNotSupportedError: en_core_web_lg version 3.1.0 error

### ISSUE THREAD

**Issue by EmanAman** [msg-systems/coreferee#51]
Python version: 3.9.7
Spacy: Version: 3.1.0
Model: en-core-web-lg Version: 3.1.0

I'm trying the following code:

python -m coreferee install en_core_web_lg
import coreferee 
import spacy

nlp = spacy.load('en_core_web_lg')
nlp.add_pipe('coreferee')

I've tried using different models but all of them keep giving me the same error: 
ModelNotSupportedError: en_core_web_lg version 3.1.0

Any help would be appreciated.

**Comment by richardpaulhudson** [comment]
Hi, rather than the install command you give, you should use

```
python -m spacy download en_core_web_lg
python -m coreferee install en
```

**Comment by EmanAman** [comment]
Thank you that seemed to work.
