### ISSUE TITLE
What about Noun phrases mentions?

### ISSUE THREAD

**Issue by hamzaelouiaazzani** [msg-systems/coreferee#54]
Hello everyone,
I see that this model is trained to only deal with single words, Does its architecure not based on span representation?
Sometimes a mention is composed of several words and not with one word; can anyone please explain to me this issue ?

**Comment by Pantalaymon** [comment]
Hello,

The data model is indeed based on tokens which has its cons and pros.
You should be able to retrieve the span corresponding to the tokens by using the subtree , for instance :
`
mention = doc[token.left.i:token.right.i]
`
Although it is dependeng on spacy's parse tree (so not necessarily totally accurate) and you should do some tweaking to add some extra rules to include or exclude some parts of the subtree. [Here](https://github.com/Pantalaymon/coreferee_french/blob/main/build_mentions.py) is an example of what I did for french to achieve this, getting inspiration from this for english should not be too difficult.
