### ISSUE TITLE
Python 3.9 support?

### ISSUE THREAD

**Issue by prrao87** [msg-systems/coreferee#6]
Hi there, thanks a lot for publishing this -- looking forward to trying it out! I was trying to build this for Python 3.9, but it looks like the setup.py forces it to be >=3.8 and <3.9. Is there any fundamental reason why this won't work with Python 3.9?

**Comment by richardpaulhudson** [comment]
Hi @prrao87, at the time of publication TensorFlow did not yet support Python 3.9. In the meantime TensorFlow 2.5.0 has been released, so the next version of Coreferee will certainly support Python 3.9. Although I haven't tested it yet, there's no fundamental reason why I would expect the current codebase not to work with Python 3.9, so you could try downloading the source code and changing the `python_requires` directive.
